### ISSUE TITLE
Problems about system calls whitelist

### ISSUE THREAD

**Issue by virusdefender** [DMOJ/judge#180]
I'm confused after reading your code briefly especially https://github.com/DMOJ/judge/blob/master/dmoj/cptbox/syscalls.py  . 

Are you using system calls whitelist for different languages? If yes, can you give me the code location and short explanation?

Thanks!

**Comment by Xyene** [comment]
Hi,

Yes, all languages have a syscall whitelist. The syscalls allowed to all languages can be found [here](https://github.com/DMOJ/judge/blob/master/dmoj/cptbox/chroot.py#L14). Most languages require additional syscalls to run, for example [Haskell](https://github.com/DMOJ/judge/blob/master/dmoj/executors/HASK.py#L11). Syscalls specified in that list are added to those specified in the global list.

Some languages are particularly problematic in that they don't function without access to some potentially dangerous syscalls (e.g., [Mono](https://github.com/DMOJ/judge/blob/master/dmoj/executors/mono_executor.py#L96-L106) without `sys_socket` + others), in which cases you can specify custom handlers for those particular syscalls.

On a final note, you may notice that the global whitelist allows `sys_clone` which could potentially be a security risk, but unless an executor specifies otherwise with the `nproc` attribute, we set `RLIMIT_NPROC` to 0.

Hope that answers your question!

**Comment by virusdefender** [comment]
Got it, thanks a lot!
