### ISSUE TITLE
Uncleaned wbox accounts

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#19]
When `wbox` crashes, its generated accounts are never cleaned. They should be cleaned the next time the judge boots.

```
C:\Users\Tudor>net user

User accounts for \\BERLIN

-------------------------------------------------------------------------------
Administrator            Guest                    Tudor
-----------              wbox0000000000c6afaf     wbox0000000001871be0
wbox00000000018a93b8     wbox000000000191d021     wbox0000000001aa8ccc
wbox0000000001b196a0     wbox000000000ace72e2     wbox000000000b23e734
wbox000000000b296475     wbox000000000b324dc7     wbox000000000ba9c9f5
wbox000000000bb804e8     wbox000000000bbb3434
The command completed successfully.
```

**Comment by quantum5** [comment]
Proposed implementation is to use `wbox<judge name>`. Judge name should be unique because the bridge would otherwise reject authentication attempt, and we don't have parallel grading.

On startup, such accounts would be deleted on sight. The admin can also easily use the task scheduler to clean up such accounts if necessary, before shutdown.

**Comment by Xyene** [comment]
Temporary solution:

```batch
@echo off
for /f %%i in ('"wmic UserAccount get Name | findstr wbox"') do net user %%i /delete
```

**Comment by quantum5** [comment]
If your account, or better yet, your mom's account, is called `showbox`, then good luck!

**Comment by quantum5** [comment]
Tested to work.
