### ISSUE TITLE
Judge does not strip \r

### ISSUE THREAD

**Issue by BinAccel** [DMOJ/judge#228]
When sending input, the judge does not remove `\r` from input files

Example:

![image](https://cloud.githubusercontent.com/assets/15059063/21322267/57ff82f0-c5e6-11e6-9851-3a23b0e8366e.png)

Input File:

![image](https://cloud.githubusercontent.com/assets/15059063/21322284/6ee5a1f2-c5e6-11e6-8b37-dfcbf31257b2.png)

(`^M` is `\r` in VIM)

**Comment by BinAccel** [comment]
Actual file: [https://dl.dropboxusercontent.com/u/62637212/in.txt](https://dl.dropboxusercontent.com/u/62637212/in.txt)

**Comment by quantum5** [comment]
What do you think the problem is? Perhaps because your output file is wrong? This is what the file is in verbatim:

```
12
2
```

I fail to see how it could possibly compare equal to the program output? As for normalization, what we are doing is the standard way of normalizing line endings, which interprets it as two new lines. Despite this, the `standard` checker is perfectly capable of collapsing new lines, but it does serve to confuse users. 

The lessons learned are:

1. Do not use `\r\r\n` to end lines. That is asking for trouble.
2. Actually check your own files for problems before thinking you are sabotaged from the above.
