### ISSUE TITLE
Local grading server UI

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#30]
Would by highly useful for problemsetters without installing the DMOJ Django site. Could be written as a lightweight Java applet that implements a minimal grading UI. 

It would reduce the amount of effort that needs to go into organizing contests, since data would not have to be uploaded for every try. Would also be useful for allowing this judge to be used as a standalone program for private training (there are more stars on this repo than the site repo, which might be indicative that some potential users are interested in private graders).

**Comment by quantum5** [comment]
Local grading would of course be nice to have, but the current executor setup is not a trivial matter. Otherwise the implementation is should not be too hard.

We might also have to decouple the grader from the packet manager instead of using pseudo-packet manager subclasses as we once did for more sane code.

Finally, IDK if Java applet is the best solution, consider this is a python app.

**Comment by Xyene** [comment]
Explanation and justification: the Java server would be a *server* that exposes the exact same interface as the site bridge. Java would be a good language simply for how easy it is to make a functional, nontrivial UI in.

**Comment by Xyene** [comment]
RSyntaxTextPane would be nice for submission editors, with an MDI.

**Comment by quantum5** [comment]
See DMOJ/hephaestus#1, #161, and #84.
