### ISSUE TITLE
Connection refused by host on Windows

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#4]
`error: [Errno 10054] An existing connection was forcibly closed by the remote host`

**Comment by Xyene** [comment]
```
CompileError: In file included from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\cmath:44:0,
                 from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\mingw32\bits\stdc++.h:41,
                 from generator-generator.cpp:1:
c:\mingw\include\math.h: In function 'float hypotf(float, float)':
c:\mingw\include\math.h:635:30: error: '_hypot' was not declared in this scope
 { return (float)(_hypot (x, y)); }
                              ^
```

**Comment by quantum5** [comment]
https://github.com/g-truc/glm/issues/300

Known MinGW issue.

**Comment by FatalEagle** [comment]
It's a MinGW bug. Just  edit math.h manually.

**Comment by Xyene** [comment]
It may be known, but it would be best if the judge ran immediately after installation of MinGW, regardless of its issues. At the very least this issue should not exit the judge process. At most it should be reported as an IE.

**Comment by quantum5** [comment]
Your MinGW deployment should be patched before you use it.

**Comment by quantum5** [comment]
A typical deployment scenerio for Windows judges would be downloading and unpacking an executor pack, get a proper judge.json, and start the judge. The admin is responsible for having correct external software. There is nothing the judge can do in this case, because that would involve patching another program on the same computer, which is pretty rude if you ask me.

**Comment by quantum5** [comment]
Issue should cause only IE though.
